FROM golang:1.21.1-bookworm AS build

WORKDIR /go-prometheus

COPY go.mod ./
COPY go.sum ./

RUN go mod download && go mod verify

RUN go mod tidy

COPY main.go ./

RUN go build -o /app

FROM gcr.io/distroless/base-ubuntu22

COPY --from=build /app /app

ENTRYPOINT ["/app"]