FROM golang:1.21.1-bookworm AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download && go mod verify

RUN go mod verify

COPY main.go ./

RUN go build -o /app

FROM gcr.io/distroless/base-ubuntu22.04

COPY --from=build /app /app

ENTRYPOINT ["/app"]